title: My Awesome Title
author: Zachary Kestner
email: zac.kestner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog site for Zachary Kestner that includes some hobbies and interests 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
